### PR TITLE
Multiple SPI and Smart SD handling - test

### PR DESCRIPTION
**Pull request by LinoBarreca**
We will use this place to have a feedback from testers.
**_SKR-PRO ONLY_**
(other boards are broken at the moment, don't waste your time trying to build it)

We need to test the following situations:
Printer without any sd card inserted.
Screen with sd-slot and card **in screen** sd-slot.
Screen with sd-slot and card on board.
Screen without sd-slot and card on board.

at the moment `LULZBOT_TOUCH_UI` and `MAX6675_SEPARATE_SPI` are broken.
if you have that DON'T use this version.

How to test:
Pull the sources.
Add your config files.
Compile.
Put the firmware in the onboard sd.
Put a .gcode in the onboard sd.
Turn on the printer.
Check that you can see the gcode.

### CODE REVIEW

**Comment by LinoBarreca** [comment]
@sjasonsmith @spawn32 @evg33 @evgeny-spb wanna give it a try?

**Comment by Evg33** [comment]
```
Marlin\src\sd\Sd2Card.cpp:113:23: error: no matching function for call to 'spiSend(int)'
Marlin\src\sd\Sd2Card.cpp:119:38: error: no matching function for call to 'spiSend(int)'
*** [.pio\build\BIGTREE_SKR_PRO\src\src\sd\Sd2Card.cpp.o] Error 1
```

**Comment by LinoBarreca** [comment]
> 
> 
> ```
> Marlin\src\sd\Sd2Card.cpp:113:23: error: no matching function for call to 'spiSend(int)'
> Marlin\src\sd\Sd2Card.cpp:119:38: error: no matching function for call to 'spiSend(int)'
> *** [.pio\build\BIGTREE_SKR_PRO\src\src\sd\Sd2Card.cpp.o] Error 1
> ```

image
I guess it's a config thing. wait I try to see what happens.

**Comment by LinoBarreca** [comment]
@Evg33 pull again.

**Comment by Evg33** [comment]
Compiling.... please wait...

**Comment by LinoBarreca** [comment]
@Evg33 what is your hardware?
how many sd card slots do you have? drivers in which mode? which kind of display?

**Comment by Evg33** [comment]
2 slots
onboard + BIQU BIGTREETECH TFT24 V1.1 (in reprap mode)

**Comment by LinoBarreca** [comment]
@Evg33 okay. for the test put a gcode in the onboard sdcard and leave the tft empty (no card).
See if it boots AND if it does boot see if you can see the file on the onboard sd

**Comment by Evg33** [comment]
```Compiling .pio\build\BIGTREE_SKR_PRO\src\src\sd\SdFatUtil.cpp.o
Marlin\src\sd\Sd2Card.cpp: In member function 'uint8_t Sd2Card::cardCommand(uint8_t, uint32_t)':
Marlin\src\sd\Sd2Card.cpp:113:23: error: no matching function for call to 'spiSend(int)'
     spiSend(cmd | 0x40);
                       ^
In file included from Marlin\src\sd\../inc/../HAL/./HAL_STM32/HAL.h:30:0,
                 from Marlin\src\sd\../inc/../HAL/HAL.h:26,
                 from Marlin\src\sd\../inc/MarlinConfig.h:30,
                 from Marlin\src\sd\Sd2Card.cpp:31:
d:\cod\marlinnt2\marlin\src\hal\shared\hal_spi.h:70:6: note: candidate: void spiSend(uint8_t, uint8_t)
 void spiSend(uint8_t bus_num, uint8_t b);
      ^~~~~~~
d:\cod\marlinnt2\marlin\src\hal\shared\hal_spi.h:70:6: note:   candidate expects 2 arguments, 1 provided
d:\cod\marlinnt2\marlin\src\hal\shared\hal_spi.h:89:6: note: candidate: void spiSend(uint8_t, uint32_t, byte)
 void spiSend(uint8_t bus_num, uint32_t chan, byte b);
      ^~~~~~~
d:\cod\marlinnt2\marlin\src\hal\shared\hal_spi.h:89:6: note:   candidate expects 3 arguments, 1 provided
d:\cod\marlinnt2\marlin\src\hal\shared\hal_spi.h:92:6: note: candidate: void spiSend(uint8_t, uint32_t, const uint8_t*, size_t)
 void spiSend(uint8_t bus_num, uint32_t chan, const uint8_t* buf, size_t n);
      ^~~~~~~
d:\cod\marlinnt2\marlin\src\hal\shared\hal_spi.h:92:6: note:   candidate expects 4 arguments, 1 provided
```

**Comment by LinoBarreca** [comment]
@Evg33 it looks like you don't have the code from https://github.com/LinoBarreca/Marlin/pull/4/commits/ac0493ac760841540c4552063ae723c4aa90ca4b and later.

**Comment by Evg33** [comment]
BIGTREE_SKR_PRO          SUCCESS

**Comment by LinoBarreca** [comment]
:crossed_fingers:

**Comment by Evg33** [comment]
No media....
I'll try to change
#define SD_DETECT_PIN -1

**Comment by LinoBarreca** [comment]
Wait. I give it a look.

**Comment by LinoBarreca** [comment]
Found the reason. wait.

**Comment by LinoBarreca** [comment]
Pull again and retry.

**Comment by LinoBarreca** [comment]
WAIT.

**Comment by LinoBarreca** [comment]
..getting there...

**Comment by Evg33** [comment]
Compiling....

**Comment by LinoBarreca** [comment]
set #define SD_DETECT_PIN -1
(for now)

**Comment by LinoBarreca** [comment]
Okay. Pull and build now.

**Comment by Evg33** [comment]
Any SD not initing at #12a1498
compiling #52fe174 ...

**Comment by LinoBarreca** [comment]
we are reeeeeeally close.... I can feel it.

**Comment by LinoBarreca** [comment]
I'll be back in 2 hours.
If it still fails toggle `SD_DETECT_INVERTED`

**Comment by Evg33** [comment]
No... Media released....
Compiling with undefined SD_DETECT_INVERTED ....

**Comment by sjasonsmith** [comment]
@LinoBarreca my SKR Pro is disconnected for now, I switched to a different board to test another issue. It looks like your current needs are handled. Let me know if you specifically need me to try something and I can hook the Pro back up.

**Comment by Evg33** [comment]
No... Media released....

**Comment by LinoBarreca** [comment]
Okay. It isn't working yet (but it should) I will try tomorrow to re-analyze everything and check if I did some mistake somewhere. If I don't find the mistake I necessarily need to wait for the board and debug the new code on the real hardware. (I don't want to make you do 10000 tests for me. that's too much of a hassle)..also...when I'll have the board here I can test with an oscilloscope if the pins are working as they should or not..maybe the BTT schema is wrong....but I can't tell now, without a board.

Now it's dinner time here. Have a nide day or evening you all.

**Comment by sjasonsmith** [comment]
Let me know if you have specific behaviors you would like me to scope for you.

**Comment by akselii** [comment]
Tested the OnBoardSD branch just now, mine wont even boot correctly with the latest commits. LCD backlight comes on but nothing else, no usb connection etc. Screen i have is fysetc mini12864.
edit: 
I think i broke the included microsd that came with the board due to many removes and inserts, i really wish there was a better way of flashing the firmare.

**Comment by LinoBarreca** [comment]
@sjasonsmith first test is easy (without involving the oscilloscope)
Connect it to serial monitor and boot it up without a sd card.
It should print out "Searching for SD card" three times (screen, board, expansion) and then "SD init fail"

if you put a card in the screen reader, it should print "Searching for SD card" one time and then "SD card found"

if you put a card in the onboard SD it should print "Searching for SD card" 2 times (screen, board) and then, if it finds the card, it should print "SD card found". if, with the SD inserted on board you get three times "Searching for SD card" it means there's something wrong with the pinout because the card doesn't answer...and the oscilloscope is needed to check is the pins get the signal

**Comment by LinoBarreca** [comment]
@akselii does the screen have an onboard sd card? Do you know how to use the serial monitor?

**Comment by akselii** [comment]
Yes it has an onboard sd card, doesnt matter if i try to boot with sd card in it or out of it. By serial monitor i guess you mean like hooking up to some pins? I dont have the hardware for it

**Comment by LinoBarreca** [comment]
no, just the USB to the computer it should be recognized as serial port

**Comment by LinoBarreca** [comment]
like "com1" (on windows)... you open the serial port and see the debugging messages

**Comment by akselii** [comment]
Yeah it doesn not show up, as in i think it does not boot at all

**Comment by Evg33** [comment]
@akselii : wait 20-40 sec. Lag after marlin logo....

**Comment by LinoBarreca** [comment]
@akselii well...no..it should boot and then crash. you don't see anything on the screen because the UI doesn't get updated after the crash....but it definitely should print something on the com when you open it. (because it resets the board so it's like "powering up the board") but nevermind I will look at it again tomorrow and see if I find a logical flaw somewhere.
@Evg33  He doesn't even see the logo....debugging this through "comments" is gonna be hard.

**Comment by akselii** [comment]
Yeah now its working, im getting the Searching for SD card. It wasnt showing up on device manager just now so i tought it was completelly dead.

**Comment by LinoBarreca** [comment]
> 
> Yeah now its working, im getting the Searching for SD card. It wasnt showing up on device manager just now so i tought it was completelly dead.

How many "Searching for SD card" do you see?

**Comment by akselii** [comment]
Just 1, booting without sd on screen, just the onboard one.

**Comment by LinoBarreca** [comment]
does it give some other message after that?

**Comment by LinoBarreca** [comment]
to test it again leave it connected, close com and reopen com

**Comment by LinoBarreca** [comment]
@evg33 since the behavior is different on your end, can you please do the same test and let us know?

**Comment by akselii** [comment]
No messages after that
Tested with and without sd card on the screen.

**Comment by LinoBarreca** [comment]
@akselii if you take "NewTimer" does the SD work from the screen?

**Comment by akselii** [comment]
Yeah, seems like it does. Atleast i can see the files on the SD card, but navigating in that menu is weirdly laggy.

**Comment by LinoBarreca** [comment]
that is weird 'cause now the first search is made on the screen sd card....and it should work like before....let me see if I find something. I'll be back.

**Comment by Evg33** [comment]
@LinoBarreca I can test tomorrow.
Now the board is far from me.

**Comment by LinoBarreca** [comment]
@akselii I pushed another commit which should solve your "freeze".
Can you please pull https://github.com/LinoBarreca/Marlin/pull/4/commits/da34afb2e375811c092717977ac7361cbe433fb8 , compile and tell me again the serial output?

**Comment by akselii** [comment]
Okay, compiling now.

**Comment by akselii** [comment]
Wont compile for me


Marlin\src\sd\Sd2Card.cpp:242:6: error: prototype for 'bool Sd2Card::init(uint8_t)' does not match any in class 'Sd2Card'
 bool Sd2Card::init(const uint8_t sckRateID) {
      ^~~~~~~
In file included from Marlin\src\sd\Sd2Card.cpp:39:0:
Marlin\src\sd\Sd2Card.h:124:8: error: candidate is: bool Sd2Card::init(uint8_t, uint8_t)
   bool init(const uint8_t bus_num, const uint8_t sckRateID);
        ^~~~
In file included from Marlin\src\sd\../inc/../pins/pins.h:517:0,
                 from Marlin\src\sd\../inc/MarlinConfig.h:32,
                 from Marlin\src\sd\SdFile.cpp:30:
Marlin\src\sd\../inc/../pins/stm32/pins_BIGTREE_SKR_PRO_V1.1.h:203:4: warning: #warning "You have a SPI display. The sdcard in the display slot will be used, if present at boot." [-Wcpp]
   #warning "You have a SPI display. The sdcard in the display slot will be used, if present at boot."
    ^~~~~~~
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\sd\cardreader.cpp.o
*** [.pio\build\BIGTREE_SKR_PRO\src\src\sd\Sd2Card.cpp.o] Error 1
In file included from Marlin\src\sd\../inc/../pins/pins.h:517:0,
                 from Marlin\src\sd\../inc/MarlinConfig.h:32,
                 from Marlin\src\sd\SdVolume.cpp:30:
Marlin\src\sd\../inc/../pins/stm32/pins_BIGTREE_SKR_PRO_V1.1.h:203:4: warning: #warning "You have a SPI display. The sdcard in the display slot will be used, if present at boot." [-Wcpp]
   #warning "You have a SPI display. The sdcard in the display slot will be used, if present at boot."
    ^~~~~~~
In file included from Marlin\src\sd\../inc/../pins/pins.h:517:0,
                 from Marlin\src\sd\../inc/MarlinConfig.h:32,
                 from Marlin\src\sd\cardreader.cpp:23:
Marlin\src\sd\../inc/../pins/stm32/pins_BIGTREE_SKR_PRO_V1.1.h:203:4: warning: #warning "You have a SPI display. The sdcard in the display slot will be used, if present at boot." [-Wcpp]
   #warning "You have a SPI display. The sdcard in the display slot will be used, if present at boot."
    ^~~~~~~
Marlin\src\sd\cardreader.cpp:361:53: error: macro "SERIAL_PRINT" requires 2 arguments, but only 1 given
     SERIAL_PRINT("Searching for SD card on SPI bus ");
                                                     ^
Marlin\src\sd\cardreader.cpp: In static member function 'static void CardReader::mount()':
Marlin\src\sd\cardreader.cpp:361:5: error: 'SERIAL_PRINT' was not declared in this scope
     SERIAL_PRINT("Searching for SD card on SPI bus ");
     ^~~~~~~~~~~~
Marlin\src\sd\cardreader.cpp:364:5: error: expected ';' before 'sd2card'
     sd2card.bus_num = trybus; //try on bus
     ^~~~~~~
Marlin\src\sd\cardreader.cpp:365:31: error: no matching function for call to 'Sd2Card::init(int)'
     if (sd2card.init(SPI_SPEED)) { //found a card on the bus
                               ^
In file included from Marlin\src\sd\SdVolume.h:45:0,
                 from Marlin\src\sd\SdBaseFile.h:37,
                 from Marlin\src\sd\SdFile.h:36,
                 from Marlin\src\sd\cardreader.h:34,
                 from Marlin\src\sd\cardreader.cpp:27:
Marlin\src\sd\Sd2Card.h:124:8: note: candidate: bool Sd2Card::init(uint8_t, uint8_t)
   bool init(const uint8_t bus_num, const uint8_t sckRateID);
        ^~~~
Marlin\src\sd\Sd2Card.h:124:8: note:   candidate expects 2 arguments, 1 provided
*** [.pio\build\BIGTREE_SKR_PRO\src\src\sd\cardreader.cpp.o] Error 1

**Comment by LinoBarreca** [comment]
weird... travis passes... wait. brb

**Comment by akselii** [comment]
Im trying something, might be my fault

**Comment by LinoBarreca** [comment]
I'm checking as well meanwhile.

**Comment by akselii** [comment]
Yeah, i think i had something going on but its still not compiling. Different error this time. I deleted the whole folder and tried again with a completelly fresh copy, copied my configuration files and changed default_envs to bigtree_skr_pro


Marlin\src\sd\Sd2Card.cpp:242:6: error: prototype for 'bool Sd2Card::init(uint8_t)' does not match any in class 'Sd2Card'
 bool Sd2Card::init(const uint8_t sckRateID) {
      ^~~~~~~
In file included from Marlin\src\sd\Sd2Card.cpp:39:0:
Marlin\src\sd\Sd2Card.h:124:8: error: candidate is: bool Sd2Card::init(uint8_t, uint8_t)
   bool init(const uint8_t bus_num, const uint8_t sckRateID);
        ^~~~
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\sd\SdVolume.cpp.o
*** [.pio\build\BIGTREE_SKR_PRO\src\src\sd\Sd2Card.cpp.o] Error 1

**Comment by LinoBarreca** [comment]
it builds good on my end...but it shouldn't because there's really an error. wait. I clean and rebuild from zero.

**Comment by LinoBarreca** [comment]
sorry mate. try again now.

**Comment by akselii** [comment]
Building

**Comment by akselii** [comment]
Without SD card on screen it goes Searching for SD card on SPI bus 0, 1, 2 and then Error:volume.init failed

**Comment by akselii** [comment]
with sd card on the screen it says SD card found and SD card ok.

**Comment by LinoBarreca** [comment]
OK. can you browse files on the "screen sd card"?
Other test: put a sd card on board and take out the one in the screen. reboot marlin. what happens?

**Comment by akselii** [comment]
Yeah, M20 returns the file list. Without card on screen and with or without sd card on board, it goes 0, 1, 2 and then error:volume.init failed

**Comment by LinoBarreca** [comment]
okay. wait. :)

**Comment by akselii** [comment]
Oh and btw, was this supposed to crash? Seems to work just fine trough the serial port. Screen is still blank tho.

**Comment by LinoBarreca** [comment]
Some screens use SPI to "write". I modified how marlin handles SPI buses so that it can have more than one. I "search" for the card probing every bus defined in the system but I still need to modify the SPI BUS used for the screen and everything will show up again. before marlin used just one bus for everything. that's why the onboard sd wasn't working. Screen or sd? of course they configured it to have the screen working.

Now Marlin has multiple buses (3 on SKR Pro).. when it starts it probes the cards on every bus, but now it doesn't know where to "draw". it's an expected behavior. I just pushed a commit which will set a "default SPI" (which should be used by screen now)

see if you have a working sd and screen and let me know.
No more commits for today. turning off the pc.
I will read your answer from mobile but expect more work on it tomorrow, not today.

**Comment by akselii** [comment]
Okay, the screen works now and i can check the files on the card, scrolling trough the list is real laggy. I lost usb connection for some reason, just stopped working even before trying the latest commit.
edit: Okay i think the usb thing was my fault, forget about it.

**Comment by LinoBarreca** [comment]
It's laggy because the screen spi is used twice (expected. It will go away once I revert last commit made for you and change properly the screen output procedures to use the same bus of sdcard)

**Comment by Spawn32** [comment]
Sorry i can't help out at the moment, putting all the electronics into a case :/

**Comment by Evg33** [comment]
1. no cards:
```
>M21
echo:Searching for SD card on SPI bus
0
echo:Searching for SD card on SPI bus
1
echo:Searching for SD card on SPI bus
2
echo:SD init fail
ok

```
2. Only onboard SD:
```
M21
echo:Searching for SD card on SPI bus
0
echo:Searching for SD card on SPI bus
1
echo:Searching for SD card on SPI bus
2
echo:SD init fail
ok
>M20
Begin file list
End file list
ok

```

3. Only LCD SD:
```
>M21
echo:Searching for SD card on SPI bus
0
echo:SD card found
echo:SD card ok
ok
>M20
Begin file list
0-SKR1~1.GCO 2698867
End file list
ok

```
4. OnBoard SD+LCD SD:
```
>M21
echo:Searching for SD card on SPI bus
0
echo:SD card found
echo:SD card ok
ok
>M20
Begin file list
0-SKR1~1.GCO 2698867
End file list
ok

```

**Comment by LinoBarreca** [comment]
okay. 1, 3 and 4 are as expected.
See if something changes with this.
https://github.com/LinoBarreca/Marlin/pull/4/commits/2b90292721d7d39644d2491cd37674f1674dc54a

if it doesn't I suspect that the board schema is wrong and I need the board and the Oscilloscope.
According to the documentation 
image
even if the bootloader from BTT disabled the SPI on TF. it should be enabled again when trying to access it....so if with the latest commit it doesn't work it's because the "pinout" in the schema is wrong.

**Comment by Evg33** [comment]
Compiling 2b90292....

**Comment by Evg33** [comment]
Only onboard sd:

```
>M21
echo:Searching for SD card on SPI bus
0
echo:Searching for SD card on SPI bus
1
echo:Searching for SD card on SPI bus
2
echo:SD init fail
ok

>M20
Begin file list
End file list
ok

```

**Comment by LinoBarreca** [comment]
can you please try again with last commit?

**Comment by LinoBarreca** [comment]
I have a strange feeling.
You are designing a board. you take a component in LQFP144 form and you lay it on Eagle.
Now you have to route 4 lines from the chip to the SD slot.
This is the chip.
image
According to the board schematics provided by BTT they took the pins in yellow and routed them to the SD slot...and connected the pin in green to a LED...kinda unusual, no? if you have 4 lines close why bothering taking the line from that far? To connect a led on the pin in green? possible...but stupid...
For the "screen SD" they took the brown lines, instead.. 

Can somebody measure the voltage on PA7 with the board powered on or try the last commit?

**Comment by Evg33** [comment]
Compiling #77e639a

**Comment by Evg33** [comment]
#77e639a
```
M21
echo:Searching for SD card on SPI bus
0
echo:Searching for SD card on SPI bus
1
echo:Searching for SD card on SPI bus
2
echo:SD init fail
ok


```

**Comment by LinoBarreca** [comment]
when you do M21, do you have a led flashing on the board?

**Comment by Evg33** [comment]
no

**Comment by LinoBarreca** [comment]
Maybe it's too fast to see it.. but if they routed the pins as they said it should happen.
The pictures that are on the internet don't have an adequate lighting/resolution to try to understand how it's routed...
I guess I'll need to wait till I get the board to test it with an oscilloscope.

**Comment by Evg33** [comment]
Maybe @sjasonsmith can help ?
Only USB/UART connection and SD-card required for testing.

**Comment by LinoBarreca** [comment]
I'm leaving these here, for reference, for when I'll have the board.
image
image
image

@Evg33 yes, he could. but it's something time consuming. We'll wait a couple of weeks...

**Comment by LinoBarreca** [comment]
Even a voltmeter which measure resistance could be good but we need the board

**Comment by Evg33** [comment]
[SKR_PRO_Photos.zip](https://github.com/LinoBarreca/Marlin/files/3836060/SKR_PRO_Photos.zip)

**Comment by LinoBarreca** [comment]
Thanks for the pictures. It's kinda impossible to follow the tracks through pictures...

**Comment by LinoBarreca** [comment]
but...
wait...

**Comment by LinoBarreca** [comment]
This shouldn't make it working but it's better.

**Comment by akselii** [comment]
Im pretty sure PA7 is connected to R25 on the board, if my continuity test was right. Pretty small stuff and the board is on my printer so bit hard to be sure. But voltage i measured from that resistor was 0.5v

**Comment by LinoBarreca** [comment]
@akselii I don't need the voltage. I need the continuity. Power off board, detach it from computer and every other power source and set the multimeter in "continuity mode" or "resistance"

**Comment by akselii** [comment]
Up there you said you wanted the PA7 voltage. What pin and where do you want me to check for continuity?

**Comment by LinoBarreca** [comment]
@akselii  sorry by "voltmeter" I really meant "multimeter". My bad.
above I put two numbers on the microSD port those are the SD pin numbers. Check if pin 9 SD, is connected to the red pin of the arm
image

**Comment by LinoBarreca** [comment]
there's the zoom thanks to @Evg33 
image

**Comment by akselii** [comment]
Yeah, im getting a beep when i try to probe from that left most pin on the sd card slot to there about on the arm. My probe leads could be a bit thinner for this kind of work. But the left most pin on SD card is also connected to ground

**Comment by LinoBarreca** [comment]
@akselii it should be connected to ground only if you have your card inserted. if you take it out it shouldn't be connected to gnd anymore

**Comment by akselii** [comment]
That was it. Its no longer connected to ground and im getting continuity from PB11 to that pin on the sd card

**Comment by LinoBarreca** [comment]
can you confirm, please?

**Comment by LinoBarreca** [comment]
ok, awesome.
Another check. jump one pin, go to 7.
According to BTT schema it should be connected to PA6 (and should buzz also on VDD)
image

On PA6 resistance should be around 0 while on VDD 10K

**Comment by akselii** [comment]
Yeah, seems like its connected. Didnt get a buzz from VDD (3rd pin from PA6)

**Comment by LinoBarreca** [comment]
probably because 10Kohm are enough for the tester to say "not directly connected" but it should be.
Next.
SD pin 5 with PA5
image

**Comment by akselii** [comment]
5th pin from the right is connected to PA5. The pin with the number 6 on that image you posted above

**Comment by LinoBarreca** [comment]
I fixed it lol :P

**Comment by akselii** [comment]
Yeah, had to refresh the page to see :D

**Comment by LinoBarreca** [comment]
SD pin 2 with PA4?

**Comment by akselii** [comment]
Yep

**Comment by LinoBarreca** [comment]
then I guess the SD pin 3 is really connected with PB5...or the flash of the firmware wouldn't work.

**Comment by akselii** [comment]
Didnt count the pins but i probed close enough to find continuity at least near PB5 and SD pin 3

**Comment by LinoBarreca** [comment]
Okay. So the schema from BTT seems good.
The pinout in the configuration of the variant is good at least for the SPI...maybe something else changes it? Gotta check.

**Comment by LinoBarreca** [comment]
Now there's no risk that a wrongly enabled driver could mess with our pins.
Can someone build it and test if something changed?

**Comment by Evg33** [comment]
Compiling...

**Comment by LinoBarreca** [comment]
wait I saw there's the UART too.

**Comment by LinoBarreca** [comment]
but I didn't disable it because we need it... I need to delete the pin from the list of pins available to UART

**Comment by LinoBarreca** [comment]
go.
If this still doesn't work I really have no fucking clue and I need the board....
It doesn't matter how much I will take, I will win in the end.

**Comment by Evg33** [comment]
#9027663 not working.
Recompiling at  #9a9e0b1 ...

**Comment by Evg33** [comment]
Fail.....
and serial not available via usb.....

**Comment by Evg33** [comment]
7c93f01
```
>M21
echo:Searching for SD card on SPI bus
0
echo:Searching for SD card on SPI bus
1
echo:Searching for SD card on SPI bus
2
echo:SD init fail
ok

>M20
Begin file list
End file list
ok

```

**Comment by LinoBarreca** [comment]
Evgeny, leave it.
I will ask if i need it :heart: thank you so much for your help.
Now the pins are not conflicting anymore so I'm sure that doesn't create a problem.
I will have a look at the TF initialization code. Maybe there's something which works for the display but doesn't work for the onboard (like speed..but it seems strange since the SPI1 actually supports a faster speed..maybe it's that..)
When I need a test I will write it.
Thank you again.

**Comment by Evg33** [comment]
I can continue testing tomorow...
That's all for today.

**Comment by LinoBarreca** [comment]
yeah for me too.

**Comment by LinoBarreca** [comment]
(Branch renamed to MultiSPI)

**Pull request closed without merging**
