### PR TITLE
Never pause the timer when disabling interrupts

### PR DESCRIPTION
**Pull request by sjasonsmith**
This solves the stepper interrupt problem. Unfortunately it takes us back even closer to where we started. I assume you will want to change some of it, but I am ready for a break :)

Basically, the first call to enable the interrupt calls resume(), to start the timer.
After that, it just enables and disables the interrupt directly.

I also removed the forced baud rate, which is no longer needed due to upstream changes.

### CODE REVIEW

**Comment by LinoBarreca** [comment]
Let's continue here.
I see what you did here: you basically reverted it all to use back again the HAL methods.
That's not what we want to do, in reality.
Because that is what led us to have a different HALs for each family.
The goal is to make timers.cpp/h it work without using HAL_xxxx methods...both for priority (which we will get rid of when 1.8.0 is out) and of these other hal methods.
We know that the pause/resume in the framework are actually a start/stop and not really a pause/resume.
I will dig into code to find a workaround which doesn't require us to start/stop. While being completely HAL_xxxx unbound.

**Comment by sjasonsmith** [comment]
At least we know where the problem came from now. Once I learned the source I didn’t spend time looking for a better solution.

**Comment by LinoBarreca** [comment]
you already did more than needed. thank you so much for finding where the problem lied :)

**Comment by LinoBarreca** [comment]
I think I found a way :)

**Comment by LinoBarreca** [comment]
@sjasonsmith since we did it without using HAL methods this isn't necessary anymore.

**Pull request closed without merging**
